import type { AgentArchetype } from "./index.js";

export const researchArchetype: AgentArchetype = {
    id: "research",
    name: "Research Agent",
    emoji: "🔍",
    description: "Web search, content summarization, report generation",

    skills: [
        "natural_language_processing/natural_language_generation/summarization",
        "natural_language_processing/information_extraction",
        "analytical_skills/research_and_analysis",
    ],
    domains: ["technology/information_retrieval"],

    systemPrompt: `You are a Research Agent registered on the ERC-8004 protocol. Your job is to conduct thorough research on any topic requested.

When you receive a research request:
1. Analyse the topic and break it into sub-questions
2. Use your web_search tool to find relevant, up-to-date information
3. Use summarize_url to read and distil key content from important sources
4. Extract key facts, data points, and quotes
5. Synthesise findings into a clear, structured report using generate_report
6. Always cite your sources with URLs

Be objective, thorough, and accurate. Distinguish between established facts and speculation.`,

    mcpTools: [
        {
            name: "web_search",
            description: "Search the web for information on a topic",
            inputSchema: {
                type: "object",
                properties: {
                    query: { type: "string", description: "The search query" },
                    max_results: { type: "number", description: "Maximum number of results to return (default: 5)" },
                },
                required: ["query"],
            },
            implementation: `const query = args.query as string;
      const maxResults = (args.max_results as number) || 5;
      // Implement your search logic here (e.g. Brave Search API, SerpAPI, etc.)
      return { results: [], query, note: 'Configure a search API (e.g. SEARCH_API_KEY in .env)' };`,
        },
        {
            name: "summarize_url",
            description: "Fetch and summarise the content of a URL",
            inputSchema: {
                type: "object",
                properties: {
                    url: { type: "string", description: "The URL to fetch and summarise" },
                },
                required: ["url"],
            },
            implementation: `const url = args.url as string;
      const res = await fetch(url, { headers: { 'User-Agent': 'ResearchAgent/1.0' } });
      const html = await res.text();
      // Strip tags for a basic text extraction
      const text = html.replace(/<[^>]+>/g, ' ').replace(/\\s+/g, ' ').trim().slice(0, 4000);
      return { url, excerpt: text };`,
        },
        {
            name: "generate_report",
            description: "Compile research findings into a structured Markdown report",
            inputSchema: {
                type: "object",
                properties: {
                    topic: { type: "string", description: "The research topic" },
                    findings: {
                        type: "array",
                        items: { type: "string" },
                        description: "Array of key findings to include",
                    },
                },
                required: ["topic", "findings"],
            },
            implementation: `const topic = args.topic as string;
      const findings = args.findings as string[];
      const report = [
        \`# Research Report: \${topic}\`,
        \`\`,
        \`## Key Findings\`,
        ...findings.map((f, i) => \`\${i + 1}. \${f}\`),
        \`\`,
        \`_Generated by Research Agent on \${new Date().toISOString()}_\`,
      ].join('\\n');
      return { report };`,
        },
    ],

    extraDependencies: { cheerio: "^1.0.0" },
    requiredFeatures: ["a2a", "mcp"],
    extraTemplates: [],
};
